### PR TITLE
Front four year dnd

### LINKED ISSUE #49: Build 4-year-plan calendar component
Should be able to render a 4-year calendar based on data passed in (through props maybe?).
Should be able to support drag and drop to change the 4-year calendar view. (R&D needed)
I think each block for a course can be its own component, and the calendar component is going to reuse that component. 
React Bootstrap's grid layout is going to be helpful.

### PR DESCRIPTION
**Pull request by Part-TimeWizard**
**Description**
Added DND functionality using react-beautiful-DND for the 4YP calendar component.  Needs styling and backend hookup

**Testing**
1. Run npm install (to get react-beautiful-DND package)
2. Run npm
3. Navigate to 4YP page
4. Drag around classes using the drag here handles

### CODE REVIEW

**Comment by Part-TimeWizard** [comment]
< div> instead of < p>

**Comment by xzz-wang** [comment]
Just a sidenote. I think the lock functionality is going to be very useful in these two sceneries: 1. Force-lock the classes in the quarters that have already past. 2. User lock classes to prevent unintentional edits.

So maybe we can aim to implement that functionality next. Also we might need to maintain the lock status between logins, so I think we need to think about this while talking with the backend people about data being communicated.

**Review by xzz-wang — APPROVED** [review]
Great work! I think if you can still try to refine it before merging, but so far so good! Let's merge it tmr.

**Comment by Part-TimeWizard** [comment]
> Just a sidenote. I think the lock functionality is going to be very useful in these two sceneries: 1. Force-lock the classes in the quarters that have already past. 2. User lock classes to prevent unintentional edits.
> 
> So maybe we can aim to implement that functionality next. Also we might need to maintain the lock status between logins, so I think we need to think about this while talking with the backend people about data being communicated.

Sounds good, there's a tutorial on how to do that, so I can add it in

**Pull request merged**
