### PR TITLE
add feedback for edit profile

### PR DESCRIPTION
**Pull request by Hann4266**
#PR: 
Related Issues: Tag your issue on the right panel of github page after you submit your PR
Author <@ yourself here>
Reviewers: Request reviewer on the right panel of the current page
Lable: Set lable to backend on the right panel of the current page

Description: Describe what your PR does

Added Behavior: Could be optional. Just describe it

Changed Behavior: Could be optional. Just describe it

### CODE REVIEW

**Review by xzz-wang — CHANGES_REQUESTED** [review]
A few things:
- We will need to style this page afterwards still, so please keep the page-related styles in the page-specific css module.
- Please don't ignore the error/warning messages in the terminal.
- The api doesn't work.

**Comment by lmy0125** [comment]
resolve warning and some styles

**Review by lmy0125 — APPROVED** [review]
need to fix profile page in small screen(white space at the bottom)

**Review by lmy0125 — APPROVED** [review]
good

**Review by lmy0125 — APPROVED** [review]
good

**Review by xzz-wang — APPROVED** [review]
Looking good!

**Pull request merged**
